# Generated by Django 4.2.7 on 2023-11-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
    ]
