# Generated by Django 4.2.7 on 2023-11-09 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0007_test_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='студент'),
        ),
    ]
