# Generated by Django 4.2.7 on 2023-11-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_study_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.materials', verbose_name='материалы теста'),
        ),
    ]
